[2025-04-07T01:36:01.379+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: anac_pipeline_dag.baixar_csv_anac scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-04-07T01:36:01.387+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: anac_pipeline_dag.baixar_csv_anac scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-04-07T01:36:01.388+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-07T01:36:01.399+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): baixar_csv_anac> on 2024-01-01 00:00:00+00:00
[2025-04-07T01:36:01.404+0000] {standard_task_runner.py:60} INFO - Started process 290 to run task
[2025-04-07T01:36:01.407+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'anac_pipeline_dag', 'baixar_csv_anac', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_anac_pipeline.py', '--cfg-path', '/tmp/tmpb80ina93']
[2025-04-07T01:36:01.409+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask baixar_csv_anac
[2025-04-07T01:36:01.426+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-07T01:36:01.465+0000] {task_command.py:423} INFO - Running <TaskInstance: anac_pipeline_dag.baixar_csv_anac scheduled__2024-01-01T00:00:00+00:00 [running]> on host 8a43643a16f6
[2025-04-07T01:36:01.541+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='anac_pipeline_dag' AIRFLOW_CTX_TASK_ID='baixar_csv_anac' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-04-07T01:36:01.733+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/download_csv.py", line 7, in baixar_csv_anac
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Dados%20Estat%C3%ADsticos%20do%20Transporte%20A%C3%A9reo/2023_Dados_Estatisticos.csv
[2025-04-07T01:36:01.748+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=anac_pipeline_dag, task_id=baixar_csv_anac, execution_date=20240101T000000, start_date=20250407T013601, end_date=20250407T013601
[2025-04-07T01:36:01.758+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task baixar_csv_anac (404 Client Error: Not Found for url: https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Dados%20Estat%C3%ADsticos%20do%20Transporte%20A%C3%A9reo/2023_Dados_Estatisticos.csv; 290)
[2025-04-07T01:36:01.780+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-07T01:36:01.797+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
